package problemSolver;

import heuristicSearch.SimpleHillClimber;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class TravellingSalesman 
{
    public static void main(String[] args) 
    {
    	ProblemReader problemReader = new ProblemReader(args[0]);
    	
    	try 
    	{
    		SimpleHillClimber simpleHillClimber = new SimpleHillClimber(problemReader.getCityMap(), problemReader.getStartCity(), Integer.parseInt(args[1]));
    		simpleHillClimber.printStateAndHeuristic(simpleHillClimber.climbHill());
		} catch (NumberFormatException e)
    	{
			System.out.println("Provide a valid max number of iterations:" + e);
		}
    	
    }
}
